apiVersion: v1
kind: Service
metadata:
  name: incident-dashboard-service
  namespace: incident-dashboard
spec:
  selector:
    app: incident-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer